use_sim_time: true

navigation:
  rviz: true

  environment:
    package: "ssr_stage"
    launch_file: "multi_bot_empty.launch"
    args: {}

  mapping:
    node_package: "map_server"
    map_package: "ssr_stage"
    map_path: "maps/stage_empty.yaml"
    map_frame: "/map"
    odom_frame: ""
    map_topic: "/map"
    scan_topic: ""

#  mapping:
#    node_package: "gmapping"
#    map_package: ""
#    map_path: ""
#    map_frame: "/map"
#    odom_frame: "/odom"
#    map_topic: "/map"
#    scan_topic: "/dumper/base_scan"


  robots:
    dumper:
      namespace: "dumper"
      scan_topic: "base_scan"
      tf_prefix: "/robot_0"
      map_frame: "/map"
      odom_frame: "odom"
      base_frame: "base_link"

      move_base:
        config_package: "multi_robot_path_planner"
        config_path: "move_base_config/stage/dumper"

      localization:
        package: "fake_localization"
        footprint_frame: "base_link"

#      localization:
#        package: "amcl"
#        footprint_frame: "base_link"
#        initial_pose: {x: 1.3, y: 1.0, z: 0.0}

    digger:
      namespace: "digger"
      scan_topic: "/dumper/base_scan"
      tf_prefix: "/robot_1"
      map_frame: "/map"
      odom_frame: "odom"
      base_frame: "base_link"

      move_base:
        config_package: "multi_robot_path_planner"
        config_path: "move_base_config/stage/digger"

      localization:
        package: "fake_localization"
        footprint_frame: "base_link"

#      localization:
#        package: "amcl"
#        footprint_frame: "base_link"
#        initial_pose: {x: 1.15, y: 1.3, z: 0.0}

    transporter:
      namespace: "transporter"
      scan_topic: "/dumper/base_scan"
      tf_prefix: "/robot_2"
      map_frame: "/map"
      odom_frame: "odom"
      base_frame: "base_link"

      move_base:
        config_package: "multi_robot_path_planner"
        config_path: "move_base_config/stage/transporter"

      localization:
        package: "fake_localization"
        footprint_frame: "base_link"

#      localization:
#        package: "amcl"
#        footprint_frame: "base_link"
#        initial_pose: {x: 1.0, y: 1.0, z: 0.0}
